### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by vwrobel** [yunluyl/react-redux-mapbox-gl#2]
Hey @yunluyl !

Thank you for your reactivity!

I am using webpack for my project and get the following error when I try to use your package:

```
6:19:03 PM nodemon.1          |  /Users/vwrobel/Projects/myproject/node_modules/react-redux-mapbox-gl/Mapbox.jsx:2
6:19:03 PM nodemon.1          |  import React from 'react';
6:19:03 PM nodemon.1          |  ^^^^^^
6:19:03 PM nodemon.1          |  SyntaxError: Unexpected token import
6:19:03 PM nodemon.1          |      at Object.exports.runInThisContext (vm.js:53:16)
6:19:03 PM nodemon.1          |      at Module._compile (module.js:513:28)
6:19:03 PM nodemon.1          |      at Object.Module._extensions..js (module.js:550:10)
6:19:03 PM nodemon.1          |      at Module.load (module.js:458:32)
6:19:03 PM nodemon.1          |      at tryModuleLoad (module.js:417:12)
6:19:03 PM nodemon.1          |      at Function.Module._load (module.js:409:3)
6:19:03 PM nodemon.1          |      at Module.require (module.js:468:17)
6:19:03 PM nodemon.1          |      at require (internal/module.js:20:19)
6:19:03 PM nodemon.1          |      at Object.<anonymous> (/Users/vwrobel/Projects/myproject/node_modules/react-redux-mapbox-gl/index.js:1:80)
6:19:03 PM nodemon.1          |      at Module._compile (module.js:541:32)
```

I do not have any problems with the other packages I use with this webpack config:

```
const path = require('path');
const webpack = require('webpack');

process.env=...

const nodeEnv = process.env.NODE_ENV;

const plugins = [
  new webpack.DefinePlugin({
    'process.env': JSON.stringify(process.env)
  })
];

if (nodeEnv === 'development') {
  plugins.push(new webpack.HotModuleReplacementPlugin());
} else {
  plugins.push(new webpack.optimize.UglifyJsPlugin({ minimize: true }));
}

// project folder
const root_folder = path.resolve(__dirname, '..');

const configuration =
{
  // resolve all relative paths from the project root folder
  context: root_folder,

  // https://webpack.github.io/docs/multiple-entry-points.html
  entry: {
    bundle: (nodeEnv === 'development') ? [
      `webpack-dev-server/client?http://localhost:${process.env.WEBPACK_PORT}`,
      'webpack/hot/only-dev-server',
      'babel-polyfill',
      './src/client/client.js'
    ] : [
      'babel-polyfill',
      './src/client/client.js'
    ]
  },

  output: {
    // filesystem path for static files
    path: path.resolve(root_folder, process.env.ASSETS_DIR),

    // network path for static files
    publicPath: '/assets/',

    // file name pattern for entry scripts
    filename: '[name].[hash].js',

    // file name pattern for chunk scripts
    chunkFilename: '[name].[hash].js'
  },

  module: {
    noParse: [],
    loaders: [
      { test: /\.json$/, loader: 'json' },
      {
        test: /\.jsx?$/,
        loaders: (nodeEnv === 'development') ? ['react-hot', 'babel-loader'] : ['babel-loader'],
        exclude: /(node_modules|bower_components)/
      },
      { test: /\.css$/, loader: 'style-loader!css-loader' },
      {
        test: /\.(png|jpg|svg)$/,
        loader: 'url-loader?limit=10240' /
      },
      {
        test: /\.(mp4)$/,
        loader: 'file-loader'
      }
    ]
  },
  resolve: {
    // you can now require('file') instead of require('file.[extension]')
    extensions: ['', '.json', '.js'],
    packageMains: ['browser', 'web', 'browserify', 'main', 'style']
  },

  plugins: plugins
};

module.exports = configuration;
```

The component I try to render (your example):

```
import React, { Component } from 'react';
import Mapbox from 'react-redux-mapbox-gl';
import mapboxgl from 'mapbox-gl';

class Test extends Component {
  render() {
    const mapStyle = {
      width: 200,
      height: 300
    };

    const mapOptions = {
      style: 'mapbox://styles/mapbox/streets-v9'
    };

    return (
      <Mapbox
        mapboxgl={mapboxgl}
        accessToken='<myToken>'
        style={mapStyle}
        options={mapOptions}
      />
    );
  }
}

export default Test;
```

Do you have any idea how I could solve this problem? I have tried to rename the 'jsx' files in your module to 'js' or to change my 'jsx' loader to 'babel' with no success.

Thank you for your time!

**Comment by yunluyl** [comment]
Did this happen during webpack compile or node run?

Make sure you compile all the .jsx files using Babel with all required presets.

I have an example showing how to use this package with webpack. You can take a look.

https://github.com/yunluyl/react-redux-mapbox-gl-example

**Comment by vwrobel** [comment]
During node run. The webpack compile seems fine.

Thank you, I will work on your example and keep you informed.

my .babelrc:

```
{
  "presets": [
    "react",
    "es2015",
    "stage-0",
    "stage-1",
    "stage-2",
    "stage-3"
  ],
  "only": [
    "*.js",
    "*.jsx"
  ]
}
```

**Comment by vwrobel** [comment]
OK I have been able to tweak my webpack.config thanks to your example webpack.config and everything runs fine now. Thanks!

Yet, I have to use your module outside of my 'node_modules' folder since this dir is excluded from compilation in my webpack config (in other packages I use, modules are already compiled when I npm install them).

I will wait to have a better understanding of webpack or that other users of your package share their inputs. You can close this issue!

**Comment by yunluyl** [comment]
Thanks for your inputs! I'll update the package accordingly based on the information you provided. Let me know if you have problem using this package.
